### ISSUE TITLE
fd_ebpf correctness issue

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#1233]
**Problem**

fd_ebpf_static_link, the loader of trusted eBPF program code (i.e. XDP programs, not on-chain) has an off-by-one error.

This is not considered a security vulnerability.

```
==4118333==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x5110000008c0 at pc 0x5a340fa91dbb bp 0x7ffcd439e3d0 sp 0x7ffcd439db78
--
  | READ of size 2 at 0x5110000008c0 thread T0
  | ==4118333==WARNING: invalid path to external symbolizer!
  | ==4118333==WARNING: Failed to use and restart external symbolizer!
  | #0 0x5a340fa91dba in __interceptor_strncmp
  | #1 0x5a340fb567e9 in fd_ebpf_static_link /github/workspace/src/ballet/ebpf/fd_ebpf.c:82:14
  | #2 0x5a340fb55bc3 in LLVMFuzzerTestOneInput /github/workspace/src/ballet/ebpf/fuzz_ebpf.c:53:5
  | #3 0x5a340fa61b70 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)
  | #4 0x5a340fa4bca2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long)
  | #5 0x5a340fa516e6 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))
  | #6 0x5a340fa7a8b2 in main
  | #7 0x780ad9d37d8f in __libc_start_call_main sysdeps/nptl/libc_start_call_main.h:58:16
  | #8 0x780ad9d37e3f in __libc_start_main csu/libc-start.c:392:3
  | #9 0x5a340fa46c84 in _start
  |  
  | 0x5110000008c0 is located 0 bytes after 256-byte region [0x5110000007c0,0x5110000008c0)
  | allocated by thread T0 here:
  | #0 0x5a340fb16b9e in __interceptor_malloc
  | #1 0x5a340fb55acf in LLVMFuzzerTestOneInput /github/workspace/src/ballet/ebpf/fuzz_ebpf.c:41:11
  | #2 0x5a340fa61b70 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)
  | #3 0x5a340fa4bca2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long)
  | #4 0x5a340fa516e6 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))
  | #5 0x5a340fa7a8b2 in main
  | #6 0x780ad9d37d8f in __libc_start_call_main sysdeps/nptl/libc_start_call_main.h:58:16
  |  
  | SUMMARY: AddressSanitizer: heap-buffer-overflow (/mnt/scratch0/clusterfuzz/bot/builds/firedancer-builds.isol-clusterfuzz.appspot.com_main_libfuzzer_highend_edc749d515dd068d31e59a7c9e63e8a9f5a93220/revisions/fuzz_ebpf-highend/fuzz_ebpf-highend+0xf6dba) (BuildId: cce0dfd75e1f67b1)
  | Shadow bytes around the buggy address:
  | 0x511000000600: 00 00 00 00 00 00 00 00 fa fa fa fa fa fa fa fa
  | 0x511000000680: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  | 0x511000000700: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  | 0x511000000780: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  | 0x511000000800: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  | =>0x511000000880: 00 00 00 00 00 00 00 00[fa]fa fa fa fa fa fa fa
  | 0x511000000900: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  | 0x511000000980: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  | 0x511000000a00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  | 0x511000000a80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  | 0x511000000b00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  | Shadow byte legend (one shadow byte represents 8 application bytes):
  | Addressable:           00
  | Partially addressable: 01 02 03 04 05 06 07
  | Heap left redzone:       fa
  | Freed heap region:       fd
  | Stack left redzone:      f1
  | Stack mid redzone:       f2
  | Stack right redzone:     f3
  | Stack after return:      f5
  | Stack use after scope:   f8
  | Global redzone:          f9
  | Global init order:       f6
  | Poisoned by user:        f7
  | Container overflow:      fc
  | Array cookie:            ac
  | Intra object redzone:    bb
  | ASan internal:           fe
  | Left alloca redzone:     ca
  | Right alloca redzone:    cb
  | ==4118333==ABORTING
```

**Comment by AbhinavMir** [comment]
hi! new contributor here! I have a fix in mind, how can I test it/reproduce this? (unless already assigned)

**Comment by ripatel-fd** [comment]
@AbhinavMir I've attached the crash input to this comment (uncompress with `gunzip`). Thank you for the offer -- I'd be happy to review and merge your fix. 

[clusterfuzz-testcase-minimized-fuzz_ebpf-highend-5733131063656448.gz](https://github.com/firedancer-io/firedancer/files/14166537/clusterfuzz-testcase-minimized-fuzz_ebpf-highend-5733131063656448.gz)

There are a few ways to reproduce it:
- Compile with GCC: `make -j fuzz-test`
- Compile with Clang and instrumentation: `make -j fuzz-test EXTRAS='fuzz asan'` 

The binary can be invoked like `build/native/gcc/fuzz-test/fuzz_ebpf/fuzz_ebpf clusterfuzz-testcase-*`

**Comment by ripatel-fd** [comment]
@AbhinavMir I'm going to start working on this later today. If you already have some progress, please feel free to share it so I can incorporate your work. Thanks again.

**Comment by ripatel-fd** [comment]
https://github.com/firedancer-io/firedancer/pull/1241
https://github.com/firedancer-io/firedancer/pull/1243

**Comment by AbhinavMir** [comment]
@ripatel-fd my bad! I think I missed this. This seems to have a candidate. Should I pick something else up? Cheers.

**Comment by ripatel-fd** [comment]
@AbhinavMir No worries. I appreciate your help. Would you like to work on https://github.com/firedancer-io/firedancer/issues/1210 ?
