### ISSUE TITLE
Async signal deadlock in fd_log / FD_ONCE

### ISSUE THREAD

**Issue by mmcgee-jump** [firedancer-io/firedancer#811]
```(gdb) bt
#0  0x00007f513352912b in sched_yield () from /lib64/libc.so.6
#1  0x000000000627e129 in fd_yield () at src/util/fd_util.c:26
#2  0x0000000006233b25 in fd_log_private_cleanup () at src/util/log/fd_log.c:925
#3  0x0000000006233c64 in fd_log_private_sig_abort (sig=2, info=0x7ffe5ebc1770, context=0x7ffe5ebc1640) at src/util/log/fd_log.c:965
#4  <signal handler called>
#5  0x00007f51335298bb in sync () from /lib64/libc.so.6
#6  0x0000000006233ad0 in fd_log_private_cleanup () at src/util/log/fd_log.c:922
#7  0x00007f513354126c in __run_exit_handlers () from /lib64/libc.so.6
#8  0x00007f51335413a0 in exit () from /lib64/libc.so.6
#9  0x000000000623397e in fd_log_private_2 (level=4, now=1697739996844136477, file=0xf13ac5f "src/app/fdctl/topology.c", line=225, func=0xf13b2f0 <__func__.32139> "fd_topo_workspace_fill", 
    msg=0x7f5134a25070 "workspace footprint 18446744073555893248 not aligned to page size 0") at src/util/log/fd_log.c:864
#10 0x00000000060f39b7 in fd_topo_workspace_fill (topo=0x7ffe5ebc3bd0, wksp=0x7ffe5ebc3be8, mode=0) at src/app/fdctl/topology.c:225
#11 0x00000000060f3db2 in fd_topo_fill (topo=0x7ffe5ebc3bd0, mode=0) at src/app/fdctl/topology.c:266
#12 0x0000000006149925 in expected_pages (config=0x7ffe5ebc39d0, out=0x7ffe5ebc2608) at src/app/fdctl/configure/large_pages.c:51
#13 0x0000000006149c2b in check (config=0x7ffe5ebc39d0) at src/app/fdctl/configure/large_pages.c:98
#14 0x0000000006143ebf in configure_cmd_perm (args=0x7ffe5ebc28c0, caps=0x7ffe5ebc2950, config=0x7ffe5ebc39d0) at src/app/fdctl/configure/configure.c:60
#15 0x00000000060b19e5 in dev_cmd_perm (args=0x7ffe5ebc3960, caps=0x7ffe5ebc2950, config=0x7ffe5ebc39d0) at src/app/fddev/dev.c:36
#16 0x00000000060ad89d in main (argc=0, _argv=0x7ffe5ec21958) at src/app/fddev/main.c:131```

**Comment by mmcgee-jump** [comment]
This doesn't happen in prod builds which #ifdef this out, but it's a deficiency in the log lib of util.
